# Generated by Django 3.1 on 2021-07-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210719_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='folio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='woman',
            name='pub_reg_doc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Published Register Document no.'),
        ),
        migrations.AddField(
            model_name='woman',
            name='pub_reg_page',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Published Register Page no.'),
        ),
        migrations.AddField(
            model_name='woman',
            name='pub_reg_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Published Register Title'),
        ),
        migrations.AddField(
            model_name='woman',
            name='pub_reg_vol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Published Register Volume'),
        ),
    ]
